with-expecter: true
issue-845-fix: True
outpkg: "mock_{{.PackageName}}"
packages:
  github.com/plar/go-adaptive-radix-tree:
    # place your package-specific config here
    config:
    interfaces:
      # select the interfaces you want mocked
      Node:
        # Modify package-level config for this specific interface (if applicable)
        config:
      Iterator:
        config: