name: release
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2.1.8
        with:
          experimental: 'true'
      - run: mise run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}